language: node_js
node_js:
- 8.11.2

cache: yarn

install:
- yarn global add lerna jest
- lerna bootstrap

matrix:
  include:
  - name: Blog Pipeline
    env: PACKAGE_LOCATION=packages/blog
  - name: Shop Pipeline
    env: PACKAGE_LOCATION=packages/shop

script:
- cd $PACKAGE_LOCATION
- yarn test

deploy:
  provider: heroku
  api_key:
    secure: DWUCaI/60/FHxghh5RadzYKamMtvp0EtJKUj92YZhnnvq2j6eJlBjLiYNXLSv/ks7fb6xVFfJuiYug86Zxo36d6Z/nIIGuoU6lWcAkw/IwlU+ZC8UPcvLlXK22IV1z59Bpr0RBFqZWwI2A8IC4bJMzmVadzDBou0G3d/NWduHkngbAEl1/H/ae2Db+z1Ao4lw+hoACULNsCDq1bCVNHhoiayrKRYpQGicmJA319YxBzWB62yLVggxgDTAo3rtCZhMNCSPzUdRxf4lwZ7DK+UJNF48eecHM1yhnhKgRM4TL2xqjijcN7Yjg+SIrrT8wlRtDUHDorRowPbkdisuC92uMPFOsXBdTARzcBcQeND0ONjuQXbziPSQg4WTKzVE50Ou873+r8O8SB0BJtbEUD3rCuTN+GQn4QCZnPfzhY8vqRGOpJXdg7vmCucQzz7Q1OmUfmdY6DuMvvTxB/QuSE1mLJOdiYXO+YEyaYsDmV07J0DL5CuQKirOGN1z5FT9IhWe78kZohMNx1LZQncGmEizpMwYXp7Kr5Rlmc+gQbQglOSBxeKXsUqvf3Ap4NImO3IS0z9iY0tZqQAyhHzrZxjqb+d/vgKslqxo57Yca/YoGt+IsBwImyJxWCPMeicfQ2KnaYCdz0QVYVvsyX4k3z5g6bBFHv7VpldQd0d1yVn0r4=
  skip_cleanup: true
