language: node_js
node_js:
- 8.11.2

cache: yarn

install:
  - yarn global add lerna jest now
  - lerna bootstrap

matrix:
  include:
  - name: Blog Pipeline
    env: PACKAGE_LOCATION=packages/blog PACKAGE_NAME=lerna-monorepo-blog
  - name: Shop Pipeline
    env: PACKAGE_LOCATION=packages/shop PACKAGE_NAME=lerna-monorepo-shop

script:
  - cd $PACKAGE_LOCATION
  - yarn test

deploy:
  provider: script
  script: now --token $NOW_TOKEN
  skip_cleanup: true
  app: $PACKAGE_NAME